class Token:
    def __init__(self, kind, value=None):
        self.kind = kind
        self.value = value

INTEGER = "INTEGER"
IDENTIFIER = "IDENTIFIER"
IF_TILDE = "IF_TILDE"
LOOP_QUESTION = "LOOP_QUESTION"
PRINT = "PRINT"
END = "END"
PLUS = "PLUS"
MINUS = "MINUS"
STAR = "STAR"
SLASH = "SLASH"
AMPERSAND_AMPERSAND = "AMPERSAND_AMPERSAND"
PIPE_PIPE = "PIPE_PIPE"
BANG = "BANG"
TILDE_EQUALS = "TILDE_EQUALS"
EQUALS = "EQUALS"
COLON_EQUALS = "COLON_EQUALS"
COLON_EQUALS_QUESTION = "COLON_EQUALS_QUESTION"
LPAREN = "LPAREN"
RPAREN = "RPAREN"
EOF = "EOF"

KEYWORDS = {
    "print": PRINT,
    "end": END,
}
