class Token:
    def __init__(self, kind, value=None):
        self.kind = kind
        self.value = value

INTEGER = "INTEGER"
IDENTIFIER = "IDENTIFIER"
PRINT = "PRINT"
IMPORT = "IMPORT"
END = "END"
ELSE = "ELSE"
PLUS = "PLUS"
MINUS = "MINUS"
STAR = "STAR"
SLASH = "SLASH"
AMPERSAND_AMPERSAND = "AMPERSAND_AMPERSAND"
PIPE_PIPE = "PIPE_PIPE"
BANG = "BANG"
TILDE_EQUALS = "TILDE_EQUALS"
EQUALS = "EQUALS"
COLON_EQUALS = "COLON_EQUALS"
COLON_EQUALS_QUESTION = "COLON_EQUALS_QUESTION"
LPAREN = "LPAREN"
RPAREN = "RPAREN"
STRING = "STRING"
DOT = "DOT"
EOF = "EOF"

IF = "IF"
LOOP = "LOOP"
SWITCH = "SWITCH"
BREAK = "BREAK"
READ = "READ"

EQUALS_TILDE = "EQUALS_TILDE"
TILDE_LESS = "TILDE_LESS"
GREATER_TILDE = "GREATER_TILDE"
TILDE_MINUS = "TILDE_MINUS"

KEYWORDS = {
    "print": PRINT,
    "read": READ,
    "import": IMPORT,
    "if": IF,
    "else": ELSE,
    "loop": LOOP,
    "switch": SWITCH,
    "break": BREAK,
    "end": END,
}
